checks:
    javascript: true

build:
    dependencies:
        #before:
            #- npm install istanbul   # or add it as part of your package.json

    tests:
        override:
            -
                #command: 'istanbul cover --report clover test.js'
                command: 'npm test -- --coverage'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
filter:
    excluded_paths:
        - "coverage/"            # Everything in a root level "coverage" directory
        - "src/registerServiceWorker.js"
